image: docker:18.09.3

services:
   - docker:18.09.3-dind

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

stages:
 - build

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker-build:
 stage: build
 script:
   - docker pull $CI_REGISTRY_IMAGE:latest || true
   - docker build --tag $CI_REGISTRY_IMAGE:latest .
   - docker push $CI_REGISTRY_IMAGE:latest
